# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: MyAgentsPool

variables:
  brpatch: $[counter(variables['build.sourcebranchname'], 0)]

steps:
- task: Maven@1
  inputs:
    mavenPomFile: 'myapp/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
    options: 'clean package -Dbrpatch=$(brpatch)'

- task: CmdLine@2
  inputs:
    script: 'java -jar myapp/target/myapp-1.0.$(brpatch).jar'

- task: CopyFiles@2
  inputs:
    Contents: 'myapp/target/myapp*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Build Artifacts'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'nicorafael/helloworld'
    command: 'buildAndPush'
    Dockerfile: 'helloworld.dockerfile'